connection:
  device_type: cisco_ios
  switch_ip: 10.101.100.10
configuration:
  int_type: GigabitEthernet
  int_range_start: 1
  int_range_end: 23
  data_vlan: 104
  voice_vlan: 190
  network_bit_octets: 10.101.100.
credentials:
  - username: user1
    password: pass1
  - username: user2
    password: pass2
  - username: user3
    password: pass3
  - username: admin
    password: password
